# Site Settings
baseurl: ""
url : "https://cliffordEmmanuel.github.io"

# Blog Settings
theme_settings :
  title : Clifford's Portfolio
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/profile-pic.jpg
    username : Clifford E. Akai-Nettey
    description : Learning how to drive business and social value using Python, Excel and SQL.
        
  # Icons
  icons :
    email:  cliffemmanuels@gmail.com
    linkedin:  https://www.linkedin.com/in/cliffordemmanuelakai-nettey/
    github: cliffordEmmanuel
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:
    

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
